@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package redcrafter07.processed.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;